Repository rust-lang/mdBook, pull requests merged in 2025-08, with the labels that each got.

#2779 Switch all public types to non_exhaustive
  Cargo.toml
  crates/mdbook-core/src/book.rs
  crates/mdbook-core/src/config.rs
  crates/mdbook-driver/src/builtin_preprocessors/index.rs
  crates/mdbook-driver/src/builtin_preprocessors/links.rs
  crates/mdbook-driver/src/builtin_renderers/markdown_renderer.rs
  crates/mdbook-driver/src/load.rs
  crates/mdbook-driver/src/mdbook.rs
  crates/mdbook-driver/src/mdbook/tests.rs
  crates/mdbook-html/src/html_handlebars/hbs_renderer.rs
  crates/mdbook-html/src/html_handlebars/search.rs
  crates/mdbook-html/src/theme/mod.rs
  crates/mdbook-preprocessor/src/lib.rs
  crates/mdbook-renderer/src/lib.rs
  crates/mdbook-summary/src/lib.rs
  examples/nop-preprocessor.rs
  tests/testsuite/renderer.rs
  tests/testsuite/search.rs
Labels: Breaking Change, S-waiting-on-review

#2783 Remove legacy config support
  crates/mdbook-core/src/config.rs
  crates/mdbook-core/src/utils/toml_ext.rs
Labels: Breaking Change, S-waiting-on-review

#2784 Add debug option to the testsuite
  tests/testsuite/book_test.rs
Labels: S-waiting-on-review

#2786 Add read_to_string to the prelude
  tests/testsuite/main.rs
  tests/testsuite/search.rs
  tests/testsuite/toc.rs
Labels: S-waiting-on-review

#2788 Remove curly-quotes
  crates/mdbook-core/src/config.rs
  crates/mdbook-driver/src/mdbook.rs
  crates/mdbook-html/src/html_handlebars/hbs_renderer.rs
  guide/src/format/configuration/renderers.md
Labels: Breaking Change, S-waiting-on-review

#2789 Remove book.json warning
  crates/mdbook-driver/src/mdbook.rs
Labels: S-waiting-on-review

#2792 Remove legacy relative renderer command paths
  crates/mdbook-driver/src/builtin_renderers/mod.rs
  tests/testsuite/renderer.rs
Labels: Breaking Change, S-waiting-on-review

#2794 Replace navigation helpers with objects
  crates/mdbook-html/front-end/css/chrome.css
  crates/mdbook-html/front-end/templates/index.hbs
  crates/mdbook-html/src/html_handlebars/hbs_renderer.rs
  crates/mdbook-html/src/html_handlebars/helpers/mod.rs
  crates/mdbook-html/src/html_handlebars/helpers/navigation.rs
  guide/src/format/theme/index-hbs.md
Labels: Breaking Change

#2795 Remove theme_option
  crates/mdbook-html/src/html_handlebars/hbs_renderer.rs
  crates/mdbook-html/src/html_handlebars/helpers/mod.rs
  crates/mdbook-html/src/html_handlebars/helpers/resources.rs
  crates/mdbook-html/src/html_handlebars/helpers/theme.rs
Labels: Breaking Change, S-waiting-on-review

#2796 Change CmdPreprocessor to use paths relative to the book root
  crates/mdbook-driver/src/builtin_preprocessors/cmd.rs
  crates/mdbook-driver/src/builtin_renderers/mod.rs
  crates/mdbook-driver/src/lib.rs
  crates/mdbook-driver/src/mdbook.rs
  crates/mdbook-driver/src/mdbook/tests.rs
  tests/testsuite/book_test.rs
  tests/testsuite/preprocessor.rs
Labels: Breaking Change, S-waiting-on-review

#2797 Add `optional` field for preprocessors
  crates/mdbook-driver/src/builtin_preprocessors/cmd.rs
  crates/mdbook-driver/src/builtin_renderers/mod.rs
  crates/mdbook-driver/src/lib.rs
  crates/mdbook-driver/src/mdbook.rs
  crates/mdbook-driver/src/mdbook/tests.rs
  crates/mdbook-preprocessor/src/lib.rs
  examples/nop-preprocessor.rs
  guide/src/format/configuration/preprocessors.md
  tests/testsuite/preprocessor.rs
  tests/testsuite/preprocessor/missing_optional_not_fatal/book.toml
  tests/testsuite/preprocessor/missing_optional_not_fatal/src/SUMMARY.md
  tests/testsuite/preprocessor/missing_preprocessor/book.toml
  tests/testsuite/preprocessor/missing_preprocessor/src/SUMMARY.md
  tests/testsuite/renderer.rs
Labels: Breaking Change, S-waiting-on-review

#2799 Use consistent sentence case for section headers
  CONTRIBUTING.md
  guide/src/SUMMARY.md
  guide/src/cli/README.md
  guide/src/continuous-integration.md
  guide/src/for_developers/README.md
  guide/src/for_developers/backends.md
  guide/src/for_developers/preprocessors.md
  guide/src/format/configuration/environment-variables.md
  guide/src/format/configuration/general.md
  guide/src/format/configuration/preprocessors.md
  guide/src/format/configuration/renderers.md
  guide/src/format/markdown.md
  guide/src/format/mathjax.md
  guide/src/format/mdbook.md
  guide/src/format/theme/editor.md
  guide/src/format/theme/index-hbs.md
  guide/src/format/theme/syntax-highlighting.md
  guide/src/guide/README.md
  guide/src/guide/creating.md
  guide/src/guide/reading.md
Labels: S-waiting-on-review

#2800 Don't serialize the default for `book.src`
  crates/mdbook-core/src/config.rs
  tests/testsuite/init.rs
  tests/testsuite/renderer.rs
Labels: S-waiting-on-review

#2807 Test and add a fix for multiple footnotes in a row
  crates/mdbook-markdown/src/lib.rs
  tests/testsuite/markdown/footnotes/expected/footnotes.html
  tests/testsuite/markdown/footnotes/src/footnotes.md
Labels: S-waiting-on-review

#2809 Introduce options struct for markdown rendering
  crates/mdbook-html/src/html_handlebars/hbs_renderer.rs
  crates/mdbook-html/src/html_handlebars/search.rs
  crates/mdbook-html/src/lib.rs
  crates/mdbook-markdown/src/lib.rs
  crates/mdbook-markdown/src/tests.rs
  tests/testsuite/markdown.rs
Labels: Breaking Change, S-waiting-on-review

#2815 add test: invalid field in the top level rust table in config
  tests/testsuite/config.rs
Labels: S-waiting-on-review

#2817 Update eslint to 9.34.0
  .eslintrc.json
  crates/mdbook-html/front-end/js/book.js
  eslint.config.mjs
  package.json
Labels: S-waiting-on-review

#2818 Lint HBS JS templates
  crates/mdbook-html/front-end/templates/toc.js.hbs
  eslint.config.mjs
  package.json
Labels: S-waiting-on-review

#2819 Various test improvements
  Cargo.lock
  Cargo.toml
  tests/testsuite/book_test.rs
Labels: S-waiting-on-review

#2821 Add the ability to pass options to browser-ui-test
  tests/gui/runner.rs
Labels: S-waiting-on-review

#2824 Add a test for extension compatibility
  tests/testsuite/book_test.rs
  tests/testsuite/preprocessor.rs
  tests/testsuite/preprocessor/extension_compatibility/book.toml
  tests/testsuite/preprocessor/extension_compatibility/src/SUMMARY.md
  tests/testsuite/preprocessor/extension_compatibility/src/chapter_1.md
  tests/testsuite/preprocessor/extension_compatibility/src/part/chapter.md
  tests/testsuite/preprocessor/extension_compatibility/src/part/sub-chapter.md
  tests/testsuite/preprocessor/extension_compatibility/src/prefix.md
  tests/testsuite/preprocessor/extension_compatibility/src/suffix.md
Labels: S-waiting-on-review
